version: '3'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "8081:8080"
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434
    extra_hosts:  
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/backend/data